//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verify", ReplyAction="http://tempuri.org/IService1/verifyResponse")]
        string verify(string xml, string xsd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verify", ReplyAction="http://tempuri.org/IService1/verifyResponse")]
        System.Threading.Tasks.Task<string> verifyAsync(string xml, string xsd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xpathsearch", ReplyAction="http://tempuri.org/IService1/xpathsearchResponse")]
        string xpathsearch(string xml, string xpath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/xpathsearch", ReplyAction="http://tempuri.org/IService1/xpathsearchResponse")]
        System.Threading.Tasks.Task<string> xpathsearchAsync(string xml, string xpath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IService1>, WebApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string verify(string xml, string xsd) {
            return base.Channel.verify(xml, xsd);
        }
        
        public System.Threading.Tasks.Task<string> verifyAsync(string xml, string xsd) {
            return base.Channel.verifyAsync(xml, xsd);
        }
        
        public string xpathsearch(string xml, string xpath) {
            return base.Channel.xpathsearch(xml, xpath);
        }
        
        public System.Threading.Tasks.Task<string> xpathsearchAsync(string xml, string xpath) {
            return base.Channel.xpathsearchAsync(xml, xpath);
        }
    }
}
